# Generated by Django 3.1.7 on 2021-11-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
